version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_employees
    restart: always
    command: --innodb_redo_log_capacity=1073741824
    environment:
      MYSQL_ROOT_PASSWORD: Qwertyz..
      MYSQL_DATABASE: employees_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge